import Link from 'next/link';
import QuoteFormCard from '@/components/QuoteFormCard';
import DigitalBidForm from '@/components/DigitalBidForm';
import { chartAssets, gallery, pages, services, site, trustItems } from '@/lib/site';

type Key = keyof typeof pages;

export default function ReferencePage({pageKey, mode='service'}:{pageKey:Key, mode?:'home'|'service'|'charts'|'bid'|'contact'|'reviews'|'legal'}){
 const page=pages[pageKey];
 return <main className="route-layout"><section className="hero-locked"><div className="hero-bg" style={{backgroundImage:`url(${page.image})`}}/><div className="hero-shade"/><div className="hero-inner"><div><span className="eyebrow">{page.eyebrow}</span><h1 className="hero-title">{page.title}</h1><p className="hero-copy">{page.copy}</p><div className="cta-row"><Link className="btn primary" href="/free-digital-bid">Start My Free Digital Bid</Link><a className="btn secondary" href={site.phoneHref}>Call {site.phone}</a></div><p className="hero-small">{site.xpsRating} • Trusted by homeowners and businesses • Project review first</p></div><QuoteFormCard/></div></section><TrustStrip/>{mode==='bid'?<BidSections/>:mode==='charts'?<ChartSections/>:mode==='contact'?<ContactSections/>:mode==='reviews'?<ReviewSections/>:<DefaultSections/>}</main>
}

function TrustStrip(){return <div className="trust-strip"><div className="trust-strip-inner">{trustItems.map(([icon,label])=><div className="trust-item" key={label}><span className="trust-icon">{icon}</span>{label}</div>)}</div></div>}

function DefaultSections(){return <><section className="section"><div className="section-head"><span className="eyebrow">Approved Floor Systems</span><h2>Choose The System. Send The Details. Get A Cleaner Bid Path.</h2><p className="muted">These are real working service sections using the approved National Epoxy Pros visual direction. Images and charts are controlled from editable data files.</p></div><div className="grid-3">{services.map(s=><Link className="service-card" href={s.href} key={s.href}><img src={s.image} alt={s.title}/><div className="card-body"><span className="tag">Explore</span><h3>{s.title}</h3><p className="muted">{s.copy}</p></div></Link>)}</div></section><section className="section alt"><div className="section-inner"><div className="section-head"><span className="eyebrow">How It Works</span><h2>Digital Bid Workflow</h2></div><div className="grid-3"><div className="process-card"><div className="card-body"><h3>1. Upload</h3><p className="muted">Photos, project details, surface condition, square footage, and inspiration.</p></div></div><div className="process-card"><div className="card-body"><h3>2. Review</h3><p className="muted">Prep, repairs, finish direction, timeline, and service area are organized for follow-up.</p></div></div><div className="process-card"><div className="card-body"><h3>3. Submit</h3><p className="muted">The form submits to the site lead endpoint and can email leads once Vercel email variables are set.</p></div></div></div></div></section><GalleryPreview/></>}

function ChartSections(){return <section className="section"><div className="section-head"><span className="eyebrow">Editable Chart Assets</span><h2>Color Charts & Finish Collections</h2><p className="muted">Charts are loaded from one editable list in <strong>lib/site.ts</strong>. Change the image path or label there and the site updates on redeploy.</p></div><div className="grid-3">{chartAssets.map(([src,label])=><div className="chart-card" key={src}><img src={src} alt={label}/><h3>{label}</h3><Link className="btn primary" href="/free-digital-bid">Use In My Bid</Link></div>)}</div></section>}

function BidSections(){return <section className="section"><div className="section-head"><span className="eyebrow">Real Lead Intake</span><h2>Submit Your Free Digital Bid</h2><p className="muted">This form posts to <strong>/api/leads</strong>. Add <strong>RESEND_API_KEY</strong> in Vercel to deliver lead emails to {site.leadsEmail}.</p></div><DigitalBidForm/></section>}

function ContactSections(){return <section className="section"><div className="split"><div><span className="eyebrow">Contact</span><h2 className="page-title">We Route Projects Carefully.</h2><p className="muted">Use this page for support, lead routing, and project questions.</p><p><strong>Phone:</strong> {site.phone}<br/><strong>Address:</strong> {site.address}<br/><strong>Support:</strong> {site.supportEmail}<br/><strong>Leads:</strong> {site.leadsEmail}<br/><strong>WhatsApp:</strong> {site.whatsapp}<br/><strong>SMS:</strong> {site.sms}</p></div><QuoteFormCard/></div></section>}

function ReviewSections(){return <section className="section"><div className="section-head"><span className="eyebrow">Reviews</span><h2>Trust Signals Require Verification.</h2><p className="muted">No fake reviews are included. Only verified testimonials should be added here.</p></div></section>}

function GalleryPreview(){return <section className="section"><div className="section-head"><span className="eyebrow">Approved Image Direction</span><h2>Visual System</h2><p className="muted">These images are editable from <strong>lib/site.ts</strong>. Replace a Drive ID or image path there to update the site.</p></div><div className="grid-3">{gallery.slice(0,8).map(g=><figure className="gallery-card" key={g.src}><img src={g.src} alt={g.title}/><figcaption className="card-body"><span className="tag">{g.tag}</span><h3>{g.title}</h3><p className="muted">Approved visual direction. Do not describe as a completed job unless separately verified.</p></figcaption></figure>)}</div></section>}
